# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60b0a324e3ab6a445aabccc7cb56befa260b1d5eb86fccf9e819e7f46c197dd15196882d72183c41864e0a227228c750eeea073d5e7fb642636b06681b1884ef

test:
  secret_key_base: 53d7ade4c84cc78b8236af403632b3ebc15eed24955a0f9af51499850554dbb6e9d9c483b63a42b150e341fdb2bd8bc1a9913463d78aeb6b3b65d2d8662a5f94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
